/// <reference path="../error.d.ts" />

/**
 * SuiteScript crypto/random module
 * @see [Help Center (Private)]{@link https://system.netsuite.com/app/help/helpcenter.nl?fid=section_13113107585}
 * @see [Help Center (Public)]{@link https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_13113107585.html}
 *
 * @module N/crypto/random
 * @NApiVersion 2.x
 */
interface random {

  /**
   * Generates cryptographically strong pseudorandom bytes.
   * @see [Help Center (Private)]{@link https://system.netsuite.com/app/help/helpcenter.nl?fid=article_0526121734}
   * @see [Help Center (Public)]{@link https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/article_0526121734.html}
   *
   * @governance 5 units (docs claim "None" but each call consumes 5 units at runtime)
   * @restriction Client-side and server-side scripts
   * @since 2023.1
   *
   * @param options
   * @param options.size The number of bytes to generate. Must be an integer between 1 and 512 inclusive. Floats are silently truncated; negative zero is treated as 0 and rejected.
   * @return A `Uint8Array` of length `options.size` containing the generated bytes.
   *
   * @throws {error.SuiteScriptError} SSS_MISSING_REQD_ARGUMENT If `options` is missing entirely, or `options` is a non-null object lacking the `size` key.
   * @throws {error.SuiteScriptError} SSS_INVALID_TYPE_ARG If `options` is `null` or a non-object primitive (string, number, etc.), or if `options.size` is `null`/`undefined`/string/boolean/array/object. Distinct from the missing-required error: missing the key produces `SSS_MISSING_REQD_ARGUMENT`, but explicitly setting it to `null`/`undefined` produces `SSS_INVALID_TYPE_ARG`.
   * @throws {error.SuiteScriptError} INVALID_NUMBER_MUST_BE_BETWEEN_1_AND_2 If `options.size` is a number outside the range 1 to 512 inclusive (including `0`, negatives, values above 512, and `Infinity`). Message format: `"Invalid number (must be between 1 and 512)"`. The `_1_` and `_2_` in the code name are placeholders for the literal bounds shown in the message.
   * @throws {error.SuiteScriptError} USER_ERROR If `options.size` is `NaN`. Same message as the out-of-range case but a different error code (NetSuite-side inconsistency).
   * @throws {error.SuiteScriptError} UNKNOWN_PARAM If `options` contains any property other than `size`. The error message is misleadingly phrased as `"Unknown parameter: size."` — it lists the RECOGNIZED parameters, not the offending ones. NetSuite-side bug in error reporting.
   */
  generateBytes(options: {
    size: number,
  }): Uint8Array;

  /**
   * Generates a cryptographically strong pseudorandom integer in the half-open range `[min, max)` —
   * `min` inclusive, `max` exclusive.
   * @see [Help Center (Private)]{@link https://system.netsuite.com/app/help/helpcenter.nl?fid=article_0526122403}
   * @see [Help Center (Public)]{@link https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/article_0526122403.html}
   *
   * @governance 5 units
   * @restriction Client-side and server-side scripts
   * @since 2023.1
   *
   * @param options
   * @param [options.min=0] Start of random range (inclusive). Defaults to `0` when omitted. Floats are accepted silently; the result is always an integer.
   * @param options.max End of random range (exclusive). Floats are accepted silently. `Infinity` and `Number.MAX_SAFE_INTEGER` are accepted without error.
   * @return A `number` (always an integer) in the half-open range `[min, max)`. **Despite the Help Center claiming a return type of `string`, the actual runtime return is `number` — verified against multiple calls.**
   *
   * @throws {error.SuiteScriptError} SSS_MISSING_REQD_ARGUMENT If `options` is missing entirely, OR `options` is a non-null object lacking the `max` key.
   * @throws {error.SuiteScriptError} SSS_INVALID_TYPE_ARG If `options` is `null` or a non-object primitive, or if `options.max` is `null`/`undefined`/string/boolean.
   * @throws {error.SuiteScriptError} INVALID_NUMBER_MUST_BE_LOWER_THAN_1 If `max <= min` (i.e. when `max` is zero or negative with default `min=0`, or when an explicit `min` equals or exceeds `max`). Message format: `"Invalid number (must be lower than max)."`.
   * @throws {error.SuiteScriptError} UNEXPECTED_ERROR If `options.max` is `NaN`. Generic message `"An unexpected SuiteScript error has occurred"` with no detail. Inconsistent with `generateBytes` which throws `USER_ERROR` for the same NaN case.
   * @throws {error.SuiteScriptError} UNKNOWN_PARAM If `options` contains any property other than `min` and `max`. As with `generateBytes`, the error message lists the recognized parameters rather than the offending ones (e.g. `"Unknown parameter: min, max."`).
   */
  generateInt(options: {
    min?: number,
    max: number,
  }): number;

  /**
   * Generates a v4 UUID using a cryptographically secure random number generator.
   *
   * Output format is the standard 8-4-4-4-12 lowercase hexadecimal representation, total length 36
   * (e.g. `'f4ffeedf-3408-418c-aa83-e5a5eee6ae55'`). Version digit is `4`; variant digit is one of
   * `8`, `9`, `a`, or `b` (RFC 4122 variant 10x).
   *
   * Accepts any arguments without validation — passing options or a primitive has no effect and
   * does not throw.
   * @see [Help Center (Private)]{@link https://system.netsuite.com/app/help/helpcenter.nl?fid=article_0526122721}
   * @see [Help Center (Public)]{@link https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/article_0526122721.html}
   *
   * @governance 5 units (docs claim "None" but each call consumes 5 units at runtime)
   * @restriction Client-side and server-side scripts
   * @since 2023.1
   *
   * @return A v4 UUID string in the format `xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx` (where `y` is `8`-`b`), length 36.
   */
  generateUUID(): string;
}
